### ISSUE TITLE
A different version of pretty_print

### ISSUE THREAD

**Issue by djiangc** [gooddata/gooddata-ruby#412]
Can I get a different implementation of pretty_print, instead of printing the MDObject.Title, please pretty the MDObject.identifier?

https://github.com/gooddata/gooddata-ruby/blob/645a671c0e988f77657b45e830fccbc5dbaead5f/lib/gooddata/goodzilla/goodzilla.rb#L38

The use case is we have a template project and a bunch of cloned objects. We would like to vaidate that cloned objects got all the correct metrics. We could have multiple objects (say, user-defined) having the same title, so pretty_print doesn't help with comparison. Neither does print, since it prints uri, and the id are different across projects.

**Comment by zsvoboda** [comment]
Do I understand correctly that printing identifiers instead of the URLs or Titles would help here? Unfortunately metric identifiers are usually automatically generated (e.g. amjpGvNcfqDG). However this probably suits your needs it isn't "pretty" representation of a metric. 

How about authoring a diff method that would compare two blueprints? Would it work?

**Comment by djiangc** [comment]
Possibly, although I am quite fuzzy about the concept of blueprints. Can you show me
1. A code snippet to generate blueprint for an existing project?
2. How to compare two blueprints?

**Comment by zsvoboda** [comment]
Please review the code snippet below. It doesn't handle metrics that you delete from the cloned project. Please let me know if this is what you wanted.

ZD

require 'gooddata'
require 'csv'
require 'pp'

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

# GoodData.logging_on



# Pretty prints the MAQL expression. This basically means it finds out names of objects and elements and print their values instead of URIs
# @param expression [String] Expression to be beautified
# @return [String] Pretty printed MAQL expression
def pp_with_identifiers(expression, opts = { client: GoodData.connection, project: GoodData.project })
  temp = expression.dup
  pairs = expression.scan(/\[([^\]]+)\]/).pmap do |uri|
    uri = uri.first
    if uri =~ /elements/
      [uri, GoodData::Attribute.find_element_value(uri, opts)]
    else
      [uri, GoodData::MdObject[uri, opts].identifier]
    end
  end

  pairs.each do |el|
    uri = el[0]
    obj = el[1]
    temp.sub!(uri, obj)
  end
  temp
end

client = GoodData.connect 'zd@gooddata.com','***'
GoodData.project = client.projects('i93usuv60yzthuuylt60mg97xjkffty7')

master_metrics = {}
metrics = GoodData.project.metrics
metrics.peach do |metric|
  master_metrics[metric.identifier]  = pp_with_identifiers metric.expression
end

GoodData.project = client.projects('pxfa5gaux5fd1tlgwofylsgjh4na2p9p')

comaprison_results = {}
metrics = GoodData.project.metrics
metrics.peach do |metric|
  if (pp_with_identifiers metric.expression).eql?(master_metrics[metric.identifier])
    # alternatively you can use the metric.identifier as the key
    comaprison_results[metric.title] = :same
  else
    # alternatively you can use the metric.identifier as the key
    comaprison_results[metric.title] = :different
  end
end

comaprison_results.each do |k,v|
  puts "#{k} : #{v}"
end

**Comment by fluke777** [comment]
@djiangc I am happy to discuss pretty printing. I am happy with the way it is but I understand there might be people with different tastes.

Your problem seems more like you are trying to visually compare something that is easy to do automatically though. If the flow you have is that you have master project and you clone additional projects. You can rely on the fact that cloned objects retain their identifiers (do not confuse with object id which is numeric). Something like this will tell you what is new and what is different. I took the liberty of rewriting what @zsvoboda is suggesting since this will also tell you what is only in one project and not the other + I think is more terse.

```ruby
require 'gooddata'

client = GoodData.connect

master_project = client.projects('pid')
cloned_project = client.projects('pid')

metrics_in_master = master_project.metrics.map(&:identifier)
metrics_in_clone = cloned_project.metrics.map(&:identifier)

in_both = metrics_in_master & metrics_in_clone
only_in_master = metrics_in_master - metrics_in_clone
only_in_clone = metrics_in_clone - metrics_in_master

puts "#{only_in_master.count} metrics are in the master but are missing in the clone"
only_in_master
  .pmap { |id| master_project.metrics(id) }
  .map {|m| puts "#{m.title} -> #{m.uri}"}

puts "#{only_in_clone.count} metrics are in the clone but are missing in the master"
only_in_clone
  .pmap { |id| cloned_project.metrics(id) }
  .map {|m| puts "#{m.title} -> #{m.uri}"}

in_both
  .pmap {|id| [master_project.metrics(id), cloned_project.metrics(id)]}
  .pselect {|mm, cm| mm.pretty_expression != cm.pretty_expression}
  .map {|mm, cm| puts "Metrics #{mm.title} -> #{mm.uri} and #{cm.title} -> #{cm.uri} have same identifier but differ in expression" }
```
Please let us know if this helps.

Regarding blueprints. They currently serve only for capturing information about models. The naming sometimes confuse people but it is basically project model just represented in JSON or ruby and It has no information specific to particular project/data_mart so you can create many project+models out of it. You can cram it into git etc. No magic there.

Information how to get blueprint is here https://github.com/gooddata/gooddata-ruby-examples/blob/master/12_working_with_blueprints/02_getting_project_blueprint.asciidoc. They should be directly comparable using == (worst case there is to_hash implemented) since internally they are represented as ruby hashes. We are still exploring how people are using it so feedback or bug reports would be highly appreciated.

**Comment by fluke777** [comment]
Closing for now. Feel free to reopen.
