### ISSUE TITLE
Add .unlisted method for MD objects

### ISSUE THREAD

**Issue by jiritobolka** [gooddata/gooddata-ruby#490]
**Use case:** I would need to check if the object is in preferred state before I migrate it to other project.

Is it possible to add method to check whether md object (report, dashboard, metric) is "unlisted"? The same way as it works for locked object. I've tried <code>report.unlisted</code> and it doesn't work

<code>
undefined method `unlisted' for #<GoodData::Report:0x007fb5c411f298>
</code>

also cannot find anything similar in the code that would solve this.

Thanks!

**Comment by fluke777** [comment]
@jiritobolka To be honest I am not aware that such flag exists. I will ask around. In the meantime you have several options.

    r = project.reports.first
    r.meta['unlisted'] == '1' # not sure about the specific condition but you get the gist

This gets the job done but it is ugly. You can do one more thing - opening a class

    class GoodData::MdObject
      def listed?
        !unlisted?
      end

      def unlisted?
       meta['unlisted'] == '1'
      end
    end

Now this would work

    r.listed? # => true

This is not completely by the book but in this case it is ok because if the unlisted flag is really present this is the interface that I would implement so your code is future compatible and once we implement it you can just remove this patch. 

Let me know if this helps

**Comment by jiritobolka** [comment]
Thanks! 

The first option did the job and it is what I needed! Thanks for other options as well ;)

JT

**Comment by fluke777** [comment]
@jiritobolka Awesome,

I learned there is unlisted flag newly in the MD. I will add the methods natively and let you know here.

**Comment by fluke777** [comment]
This should be fixed as part of

https://github.com/fluke777/gooddata-ruby/commit/8543cf33ee599ea5e0dd94d6fcee09c77010154f
